baseurl: "https://yihui.org/"
languageCode: "ru-RU"
title: "Паж при Короле"
theme: "hugo-paged"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

outputs:
  home: [html, rss, json]

permalinks:
  ru: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "Главная"
      url: "/"
      weight: 1
    - name: "О нас"
      url: "/about/"
      weight: 3
    - name: "Блог"
      url: "/ru/"
      weight: 2
    - name: "Поиск"
      url: "/search/"
    - name: "GitHub"
      url: "https://github.com/dvesti/yx"
      weight: 4
#    - name: "Vitae"
#      url: "/vitae/"
#      weight: 4
    - name: "Q&A"
      url: "https://github.com/dvesti/yx/discussions"
      weight: 5
#    - name: "Todo"
#      url: "/todo/"
#      weight: 6

  knitr:
    - name: "Home"
      url: "/knitr/"
      weight: 1
    - name: "Options"
      url: "/knitr/options/"
      weight: 2
    - name: "Hooks"
      url: "/knitr/hooks/"
      weight: 3
    - name: "Examples"
      url: "/knitr/demo/"
      weight: 4
    - name: "FAQ"
      url: "/knitr/faq/"
      weight: 5
#    - name: "Github"
#      pre: "github"
#      url: "https://github.com/yihui/knitr"
#      weight: 6
#    - name: "Yihui Xie"
#      url: "/"
#      weight: 7

params:
  description: "Сайт Ух"
  footer: "&copy; 2023--{Year} [Vladimir Dmitrijev](/)"
  customJS:
    - "comment-utils.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
#  githubContentURL: "https://github.com/yihui/yihui.org/edit/master/content/"
#  twitterImage: "/images/logo.png"

  logo:
    en:
    #  img: "/images/logo.png"
      url: "/"
      alt: LOGO TEXT
    knitr:
      img: "/knitr/images/knit-logo.png"
      url: "/knitr/"
      alt: "knitr logo"
    tinytex:
      img: "/images/logo-tinytex.png"
      url: "/tinytex/"
      alt: "tinytex logo"

  author:
    ru: Vladimir Dmitrijev

  lang:
    edit:
      ru: "Правка"
    license:
      ru: "Лицензия"
    subscribe:
      ru: "RSS"
    search:
      ru: "Поиск"
    top:
      ru: "Вверх"
    tags:
      ru: тэг
    categories:
      ru: категория

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1

